### ISSUE TITLE
[Custota SELinux rules] OSError: Exec format error

### ISSUE THREAD

**Issue by pixincreate** [chenxiaolong/my-avbroot-setup#2]
```sh
❯ python3 .tmp/my-avbroot-setup/patch.py \
--input .tmp/bluejay-ota_update-2024080600.zip \
--output .tmp/patched_ota.zip \
--verify-public-key-avb .tmp/extracted/avb_pkmd.bin \
--verify-cert-ota .tmp/extracted/ota/META-INF/com/android/otacert \
--sign-key-avb passphrase/avb.key \
--sign-key-ota passphrase/ota.key \
--sign-cert-ota passphrase/ota.crt \
--module-custota .tmp/modules/custota.zip \
--module-custota-sig .tmp/signatures/custota.zip.sig \
--module-msd .tmp/modules/msd.zip \
--module-bcr .tmp/modules/bcr.zip \
--module-oemunlockonboot .tmp/modules/oemunlockonboot.zip \
--module-alterinstaller .tmp/modules/alterinstaller.zip 
```

Executing above command in terminal throws the below attached error

```log
❯ python3 .tmp/my-avbroot-setup/patch.py \
--input .tmp/bluejay-ota_update-2024080600.zip \
--output .tmp/patched_ota.zip \
--verify-public-key-avb .tmp/extracted/avb_pkmd.bin \
--verify-cert-ota .tmp/extracted/ota/META-INF/com/android/otacert \
--sign-key-avb passphrase/avb.key \
--sign-key-ota passphrase/ota.key \
--sign-cert-ota passphrase/ota.crt \
--module-custota .tmp/modules/custota.zip \
--module-custota-sig .tmp/signatures/custota.zip.sig \
--module-msd .tmp/modules/msd.zip \                                                                                                                   <....
[*] Verifying OTA: .tmp/bluejay-ota_update-2024080600.zip
  0.000s  INFO Verifying whole-file signature
  0.860s  INFO Verifying payload
  1.998s  INFO Extracting partition images to temporary directory
  1.999s  INFO Extracting from the payload: abl, bl1, bl2, bl31, boot, dtbo, gsa, ldfw, modem, pbl, product, pvmfw, system, system_ext, tzsw, vbmeta, vendor, vendor_boot, vendor_dlkm
  8.237s  INFO Successfully extracted OTA
  8.324s  INFO Verifying partition hashes
  9.547s  INFO Checking ramdisk's otacerts.zip
  9.642s  INFO Verifying AVB signatures
  9.644s  INFO vbmeta has a signed vbmeta header
  9.644s  INFO Verifying hash descriptor for: vendor_boot
  9.644s  INFO Verifying hash descriptor for: dtbo
  9.644s  INFO Verifying hash tree descriptor for: product
  9.644s  INFO Verifying hash tree descriptor for: system_ext
  9.644s  INFO Verifying hash tree descriptor for: system
  9.644s  INFO Verifying hash tree descriptor for: vendor
  9.644s  INFO Verifying hash descriptor for: pvmfw
  9.644s  INFO Verifying hash descriptor for: boot
  9.644s  INFO Verifying hash tree descriptor for: vendor_dlkm
 13.977s  INFO Signatures are all valid!
[*] Unpacking OTA: .tmp/bluejay-ota_update-2024080600.zip
  0.002s  INFO Extracting from the payload: abl, bl1, bl2, bl31, boot, dtbo, gsa, ldfw, modem, pbl, product, pvmfw, system, system_ext, tzsw, vbmeta, vendor, vendor_boot, vendor_dlkm
  7.101s  INFO Successfully extracted OTA
[*] Unpacking AVB image: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmpvgi3d77t/images/system.img
  1.099s  INFO Verifying hash tree descriptor
[*] Unpacking filesystem: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmpvgi3d77t/system/raw.img
[*] Unpacking AVB image: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmpvgi3d77t/images/vendor.img
  0.465s  INFO Verifying hash tree descriptor
[*] Unpacking filesystem: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmpvgi3d77t/vendor/raw.img
[*] Unpacking AVB image: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmpvgi3d77t/images/vendor_boot.img
  0.029s  INFO Verifying hash descriptor
[*] Unpacking boot image: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmpvgi3d77t/vendor_boot/raw.img
[*] Unpacking CPIO archive: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmpvgi3d77t/vendor_boot/ramdisk.img.0
[*] Verifying SSH signature: .tmp/modules/custota.zip
[*] Injecting Custota: .tmp/modules/custota.zip
[*] Adding RegularFile filesystem entry: /system/etc/permissions/privapp-permissions-com.chiller3.custota.xml
[*] Adding RegularFile filesystem entry: /system/etc/sysconfig/config-com.chiller3.custota.xml
[*] Adding Directory filesystem entry: /system/priv-app/com.chiller3.custota
[*] Adding RegularFile filesystem entry: /system/priv-app/com.chiller3.custota/app-release.apk
[*] Adding Custota SELinux rules: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmpvgi3d77t/vendor/fs_tree/etc/selinux/precompiled_sepolicy
Traceback (most recent call last):
  File "/Users/me/github/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1009, in <module>
    main()
  File "/Users/me/github/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1000, in main
    run(args, Path(temp_dir))
  File "/Users/me/github/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 919, in run
    inject_custota(
  File "/Users/me/github/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 458, in inject_custota
    subprocess.check_call([
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmpqaxupelj'
```

`Custota-tool`, `AVBRoot` and `AFSR` are in paths. I had been getting into issues with `Custota` for some time now.

I created this issue just because I'm not sure whether this is an issue with the tool or me.

And yes, passing `--module-custota-sig` is mandatory without which it won't come until here. I did try to debug this to see what's wrong, I couldn't find one given that `--module-custota` is designed in the same way it is designed for other modules. See below:

```log
❯ python3 .tmp/my-avbroot-setup/patch.py \
--input .tmp/bluejay-ota_update-2024080600.zip \
--output .tmp/patched_ota.zip \
--verify-public-key-avb .tmp/extracted/avb_pkmd.bin \
--verify-cert-ota .tmp/extracted/ota/META-INF/com/android/otacert \
--sign-key-avb passphrase/avb.key \
--sign-key-ota passphrase/ota.key \
--sign-cert-ota passphrase/ota.crt \
--module-custota .tmp/modules/custota.zip \
--module-msd .tmp/modules/msd.zip \
--module-bcr .tmp/modules/bcr.zip \                                                                                                                   <....
[*] Verifying OTA: .tmp/bluejay-ota_update-2024080600.zip
  0.000s  INFO Verifying whole-file signature
  0.832s  INFO Verifying payload
  1.978s  INFO Extracting partition images to temporary directory
  1.980s  INFO Extracting from the payload: abl, bl1, bl2, bl31, boot, dtbo, gsa, ldfw, modem, pbl, product, pvmfw, system, system_ext, tzsw, vbmeta, vendor, vendor_boot, vendor_dlkm
  8.917s  INFO Successfully extracted OTA
  9.013s  INFO Verifying partition hashes
 10.072s  INFO Checking ramdisk's otacerts.zip
 10.164s  INFO Verifying AVB signatures
 10.167s  INFO vbmeta has a signed vbmeta header
 10.167s  INFO Verifying hash tree descriptor for: vendor_dlkm
 10.167s  INFO Verifying hash tree descriptor for: system_ext
 10.167s  INFO Verifying hash descriptor for: vendor_boot
 10.167s  INFO Verifying hash tree descriptor for: product
 10.167s  INFO Verifying hash descriptor for: pvmfw
 10.167s  INFO Verifying hash tree descriptor for: system
 10.167s  INFO Verifying hash descriptor for: dtbo
 10.167s  INFO Verifying hash tree descriptor for: vendor
 10.167s  INFO Verifying hash descriptor for: boot
 14.799s  INFO Signatures are all valid!
[*] Unpacking OTA: .tmp/bluejay-ota_update-2024080600.zip
  0.002s  INFO Extracting from the payload: abl, bl1, bl2, bl31, boot, dtbo, gsa, ldfw, modem, pbl, product, pvmfw, system, system_ext, tzsw, vbmeta, vendor, vendor_boot, vendor_dlkm
  8.443s  INFO Successfully extracted OTA
[*] Unpacking AVB image: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmp1kfd9ebi/images/system.img
  1.162s  INFO Verifying hash tree descriptor
[*] Unpacking filesystem: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmp1kfd9ebi/system/raw.img
[*] Unpacking AVB image: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmp1kfd9ebi/images/vendor.img
  0.512s  INFO Verifying hash tree descriptor
[*] Unpacking filesystem: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmp1kfd9ebi/vendor/raw.img
[*] Unpacking AVB image: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmp1kfd9ebi/images/vendor_boot.img
  0.035s  INFO Verifying hash descriptor
[*] Unpacking boot image: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmp1kfd9ebi/vendor_boot/raw.img
[*] Unpacking CPIO archive: /var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmp1kfd9ebi/vendor_boot/ramdisk.img.0
[*] Verifying SSH signature: .tmp/modules/custota.zip
Couldn't read signature file: No such file or directory
Could not verify signature.
Traceback (most recent call last):
  File "/Users/me/github/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1009, in <module>
    main()
  File "/Users/me/github/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1000, in main
    run(args, Path(temp_dir))
  File "/Users/me/github/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 919, in run
    inject_custota(
  File "/Users/me/github/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 420, in inject_custota
    verify_ssh_sig(module_zip, module_sig, SSH_PUBLIC_KEY_CHENXIAOLONG)
  File "/Users/me/github/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 402, in verify_ssh_sig
    subprocess.check_call([
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh-keygen', '-Y', 'verify', '-f', '/var/folders/ks/3trqc9j96ls9gxkpyd6lsk6w0000gq/T/tmpqv8i5awt', '-I', 'trusted', '-n', 'file', '-s', PosixPath('.tmp/modules/custota.zip.sig')]' returned non-zero exit status 255.
```

**Comment by chenxiaolong** [comment]
Shoot, I don't think is easily solvable. It's extracting `custota-selinux` from the module zip and running that to patch the SELinux policy. (Same thing for MSD if you didn't remove it.)

The problem is that `custota-selinux` is a Linux executable and it can't be compiled on Mac or Windows because it uses the `libsepol` C library, which is very Linux-specific. Sorry, but I think you might be stuck with using a Linux VM (directly or indirectly).

If you have docker installed, you could potentially modify the script so that it runs `custota-selinux` inside docker instead. Something like this (untested):

```bash
docker run --rm -it \
    -v /path/to/custota-selinux:/custota-selinux \
    -v /path/to/selinux/policies:/tmp \
    busybox \
    /custota-selinux -s /tmp/policy.old -t /tmp/policy.new
```

I'm currently focused on wrapping up https://github.com/chenxiaolong/afsr/issues/2, but I might look into integrating docker into the script when running on non-Linux systems.

**Comment by pixincreate** [comment]
Cool. Thanks for the response. So this is just incompatibility issue. I've been building PixeneOS on my Mac just because it gives some unix vibes unlike my Windows machine and I bet it will have even more compatibility issues.  

<strike>I'll try installing `gnu coreutils` on Mac to see if that solves the issue</strike> does not work, I'll directly push this with GHActions. Times ticking, have to rush a bit. 

I'll close this issue for now given the dependency issue.

Thanks again.

**Comment by chenxiaolong** [comment]
No problem! If you have WSL on your Windows machine, I'd recommend going with that.

**Comment by pixincreate** [comment]
`WSL` is the first I installed on my Windows machine. Its been more than a month since I last turned it on.

**Comment by pixincreate** [comment]
When I run this on Ubuntu latest GH Actions, it is throwing syntax error which I cannot reproduce locally:

```
  0.002s  INFO Extracting from the payload: abl, bl1, bl2, bl31, boot, dtbo, gsa, ldfw, modem, pbl, product, pvmfw, system, system_ext, tzsw, vbmeta, vendor, vendor_boot, vendor_dlkm
 13.905s  INFO Successfully extracted OTA
Archive:  .tmp/bluejay-ota_update-2024080600.zip
signed by SignApk
 extracting: .tmp/extracted/ota/META-INF/com/android/metadata  
 extracting: .tmp/extracted/ota/META-INF/com/android/metadata.pb  
 extracting: .tmp/extracted/ota/apex_info.pb  
 extracting: .tmp/extracted/ota/care_map.pb  
 extracting: .tmp/extracted/ota/payload.bin  
 extracting: .tmp/extracted/ota/payload_properties.txt  
  inflating: .tmp/extracted/ota/META-INF/com/android/otacert  
  File "/home/runner/work/PixeneOS/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 34
    print(f'\x1b[1m[*] {' '.join(args)}\x1b[0m', **kwargs)
                                               ^
SyntaxError: f-string: expecting '}'
```

Below is the workflow: https://github.com/pixincreate/PixeneOS/actions/runs/10448253952/job/28928428070

Do you have any thoughts on this? 

`patch.py` is in fact untouched and is only modified when `root` flag is enabled`.

Below is the command that is being executed:

```sh

  local ota_zip="${WORKDIR}/${GRAPHENEOS[OTA_TARGET]}"
  local pkmd="${KEYS[PKMD]}"
  local grapheneos_pkmd="${WORKDIR}/extracted/avb_pkmd.bin"
  local grapheneos_otacert="${WORKDIR}/extracted/ota/META-INF/com/android/otacert"
  local my_avbroot_setup="${WORKDIR}/my-avbroot-setup"

local args=()

    args+=("--input" "${ota_zip}.zip")
    args+=("--output" "${ota_zip}.patched$(dirty_suffix).zip")

    args+=(--verify-public-key-avb "${grapheneos_pkmd}")
    args+=(--verify-cert-ota "${grapheneos_otacert}")

    args+=(--sign-key-avb "${KEYS[AVB]}")
    args+=(--sign-key-ota "${KEYS[OTA]}")
    args+=(--sign-cert-ota "${KEYS[CERT_OTA]}")

    args+=(--module-custota-sig "${WORKDIR}/signatures/custota.zip.sig")
    args+=(--module-msd-sig "${WORKDIR}/signatures/msd.zip.sig")
    args+=(--module-bcr-sig "${WORKDIR}/signatures/bcr.zip.sig")
    args+=(--module-oemunlockonboot-sig "${WORKDIR}/signatures/oemunlockonboot.zip.sig")
    args+=(--module-alterinstaller-sig "${WORKDIR}/signatures/alterinstaller.zip.sig")

    args+=(--module-custota "${WORKDIR}/modules/custota.zip")
    args+=(--module-msd "${WORKDIR}/modules/msd.zip")
    args+=(--module-bcr "${WORKDIR}/modules/bcr.zip")
    args+=(--module-oemunlockonboot "${WORKDIR}/modules/oemunlockonboot.zip")
    args+=(--module-alterinstaller "${WORKDIR}/modules/alterinstaller.zip")

    python3 ${my_avbroot_setup}/patch.py "${args[@]}"
```

**Comment by pixincreate** [comment]
After spending hours to debug, I'm here, again, with an issue which I'm not sure about the root cause:

For reference: https://github.com/pixincreate/PixeneOS/actions/runs/10454228581/job/28946355661

keys are in path and are accessible. However, `patch.py` fails to load it.

```
[*] Packing filesystem: /tmp/tmppgw2dc4v/system/raw.img
[*] Packing AVB image: /tmp/tmppgw2dc4v/images/system.img
  7.180s  INFO Leaving AVB header unsigned
[*] Packing filesystem: /tmp/tmppgw2dc4v/vendor/raw.img
[*] Packing AVB image: /tmp/tmppgw2dc4v/images/vendor.img
  3.006s  INFO Leaving AVB header unsigned
[*] Packing CPIO archive: /tmp/tmppgw2dc4v/vendor_boot/ramdisk.img.0
[*] Packing boot image: /tmp/tmppgw2dc4v/vendor_boot/raw.img
[*] Packing AVB image: /tmp/tmppgw2dc4v/images/vendor_boot.img
  0.077s  INFO Leaving AVB header unsigned
[*] Patching OTA with replaced images: system, vendor, vendor_boot: .tmp/bluejay-ota_update-2024080600.patched.zip
  0.025s ERROR Failed to load key: ".tmp/avb.key"

Caused by:
    0: I/O error
    1: No such device or address (os error 6)

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
Traceback (most recent call last):
  File "/home/runner/work/PixeneOS/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1009, in <module>
    main()
  File "/home/runner/work/PixeneOS/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1000, in main
    run(args, Path(temp_dir))
  File "/home/runner/work/PixeneOS/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 973, in run
    patch_ota(
  File "/home/runner/work/PixeneOS/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 89, in patch_ota
    subprocess.check_call(cmd)
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['avbroot', 'ota', 'patch', '--input', PosixPath('.tmp/bluejay-ota_update-2024080600.zip'), '--output', PosixPath('.tmp/bluejay-ota_update-2024080600.patched.zip'), '--key-avb', PosixPath('.tmp/avb.key'), '--key-ota', PosixPath('.tmp/ota.key'), '--cert-ota', PosixPath('.tmp/ota.crt'), '--rootless', '--replace', 'system', PosixPath('/tmp/tmppgw2dc4v/images/system.img'), '--replace', 'vendor', PosixPath('/tmp/tmppgw2dc4v/images/vendor.img'), '--replace', 'vendor_boot', PosixPath('/tmp/tmppgw2dc4v/images/vendor_boot.img')]' returned non-zero exit status 1.
```

**Comment by pixincreate** [comment]
Hey there! I've got you an another problem (not sure if it is a "me" problem or not, so I'm here).  
I tried to do multiple builds with multiple fixes and after spending hours, I'm here trying to analyze where am I going wrong...

For ref: https://github.com/pixincreate/PixeneOS/actions/runs/10454228581/job/28946355661

```
[*] Packing filesystem: /tmp/tmppgw2dc4v/system/raw.img
[*] Packing AVB image: /tmp/tmppgw2dc4v/images/system.img
  7.180s  INFO Leaving AVB header unsigned
[*] Packing filesystem: /tmp/tmppgw2dc4v/vendor/raw.img
[*] Packing AVB image: /tmp/tmppgw2dc4v/images/vendor.img
  3.006s  INFO Leaving AVB header unsigned
[*] Packing CPIO archive: /tmp/tmppgw2dc4v/vendor_boot/ramdisk.img.0
[*] Packing boot image: /tmp/tmppgw2dc4v/vendor_boot/raw.img
[*] Packing AVB image: /tmp/tmppgw2dc4v/images/vendor_boot.img
  0.077s  INFO Leaving AVB header unsigned
[*] Patching OTA with replaced images: system, vendor, vendor_boot: .tmp/bluejay-ota_update-2024080600.patched.zip
  0.025s ERROR Failed to load key: ".tmp/avb.key"

Caused by:
    0: I/O error
    1: No such device or address (os error 6)

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
Traceback (most recent call last):
  File "/home/runner/work/PixeneOS/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1009, in <module>
    main()
  File "/home/runner/work/PixeneOS/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1000, in main
    run(args, Path(temp_dir))
  File "/home/runner/work/PixeneOS/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 973, in run
    patch_ota(
  File "/home/runner/work/PixeneOS/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 89, in patch_ota
    subprocess.check_call(cmd)
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['avbroot', 'ota', 'patch', '--input', PosixPath('.tmp/bluejay-ota_update-2024080600.zip'), '--output', PosixPath('.tmp/bluejay-ota_update-2024080600.patched.zip'), '--key-avb', PosixPath('.tmp/avb.key'), '--key-ota', PosixPath('.tmp/ota.key'), '--cert-ota', PosixPath('.tmp/ota.crt'), '--rootless', '--replace', 'system', PosixPath('/tmp/tmppgw2dc4v/images/system.img'), '--replace', 'vendor', PosixPath('/tmp/tmppgw2dc4v/images/vendor.img'), '--replace', 'vendor_boot', PosixPath('/tmp/tmppgw2dc4v/images/vendor_boot.img')]' returned non-zero exit status 1.
```

Do you mind helping here?  
Thanks in advance!

PS: I deleted previous comment assuming I thought I found the issue, but no, I was wrong.

Edit: I guess it is because it cannot find the `passphrase`? I now started to get that feeling. For this, I will have to modify the script if my intuition is right...

**Comment by chenxiaolong** [comment]
> Edit: I guess it is because it cannot find the `passphrase`? I now started to get that feeling. For this, I will have to modify the script if my intuition is right...

Yeah, I think you're probably right. It's probably trying to interactively prompt for the password.

I need to improve that error message though.

**Comment by pixincreate** [comment]
I have a very naive insecure approach to optionally read it from input and since I have made changes in multiple places, I felt like it is not worth using `sed` every time.  

Do you have plans to accept PRs for this repo? Asking so because I've raised one [here](https://github.com/chenxiaolong/my-avbroot-setup/pull/5)

**Comment by chenxiaolong** [comment]
In general, I don't plan to accept PRs for this repo as it is pretty specific to my own setup, but I'd be willing to add something for non-interactive use.

As far as implementation, I'd prefer if the script just accepted `--pass-avb-env-var`/`--pass-avb-file` and `--pass-ota-env-var`/`--pass-ota-file`. If those are present, then just pass them straight through to avbroot.

**Comment by chenxiaolong** [comment]
https://github.com/chenxiaolong/avbroot/pull/336 will fix the crappy error message when avbroot tries to prompt for a password without an interactive terminal.

**Comment by pixincreate** [comment]
Yay, thanks for this!
