### ISSUE TITLE
Avbroot must be in system path in order to work

### ISSUE THREAD

**Issue by 0cwa** [chenxiaolong/my-avbroot-setup#3]
Fixed by adding avbroot to path, but after Pixin downloads the ota, and starts to verify it:

```
Traceback (most recent call last):
  File "/home/x/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1009, in <module>
    main()
  File "/home/x/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1000, in main
    run(args, Path(temp_dir))
  File "/home/x/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 882, in run
    verify_ota(args.input, args.verify_public_key_avb, args.verify_cert_ota)
  File "/home/x/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 40, in verify_ota
    subprocess.check_call([
  File "/usr/lib64/python3.12/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'avbroot'
```

**Comment by pixincreate** [comment]
This seems to be an issue with the architecture. Can you verify the OS?

**Comment by 0cwa** [comment]
Fedora 40 x86; but I literally just took avbroot and afsr from their directories (.tmp/avbroot/avbroot and .tmp/afsr/target/release/afsr) and put them in ~/.local/bin and they work.  I can run them directly from shell and they work.  I'm guessing the wrong file is being run

**Comment by pixincreate** [comment]
That's what I said. Here in [declarations L9](https://github.com/pixincreate/PixeneOS/blob/7dd483f9d17418c55d6a210c8e9a95d949584562/src/declarations.sh#L9), make sure that Linux is selected.

Unset the variables since you've disabled `cleanup`. 

Try re-running the script(`src/main.sh`)

**Comment by 0cwa** [comment]
It works now! Perfect!  Edit: also afsr doesn't need to be added to the path either now

**Comment by pixincreate** [comment]
Yes, the script takes care of adding stuffs to the Path in [L224 of util_functions](https://github.com/pixincreate/PixeneOS/blob/7dd483f9d17418c55d6a210c8e9a95d949584562/src/util_functions.sh#L224)
